CREATE TABLE IF NOT EXISTS respostas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pergunta VARCHAR(255) NOT NULL,
    resposta TEXT NOT NULL,
    proxima_pergunta TEXT NOT NULL DEFAULT '',
    imagem TEXT NULL,
    menu_principal BOOLEAN NOT NULL DEFAULT FALSE,
    categoria VARCHAR(100) NULL,
    descricao TEXT NULL,
    icone VARCHAR(100) NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS respostas_pergunta_lower_idx
ON respostas (LOWER(pergunta));

CREATE TABLE IF NOT EXISTS metricas_tempo (
    tela VARCHAR(255) PRIMARY KEY,
    total_segundos DOUBLE PRECISION NOT NULL DEFAULT 0,
    visualizacoes INTEGER NOT NULL DEFAULT 0,
    ultima_atualizacao TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
